import { Metadata } from "next";
import { Inter } from "next/font/google"; // Import the Inter font
import "./globals.css";
import Navbar from "@/components/Navbar";

// Set up Inter font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased flex w-full h-screen overflow-hidden bg-background`} // Apply the Inter font
      >
        <Navbar />
        <div className="flex w-full flex-1">{children}</div>
      </body>
    </html>
  );
}
